util.AddNetworkString("SR_Tracker.SendTimeOnJoin")
util.AddNetworkString("SR_Tracker.SendTimes")
util.AddNetworkString("SR_Tracker.ChangePage")
util.AddNetworkString("SR_Tracker.Search")
util.AddNetworkString("SR_Tracker.ResetTime")

resource.AddFile("resource/fonts/Lato-Bold.ttf")

local query = SR_Tracker.MySQL:Create("sr_tracker_times")
	query:Create("steamid", "VARCHAR(255)")
	query:Create("time", "BIGINT")
	query:Create("firstjoin", "BIGINT")
	query:Create("lastjoin", "BIGINT")
	query:PrimaryKey("steamid")
query:Execute()